### ISSUE TITLE
Buinary update, pleeeaaase!

### ISSUE THREAD

**Issue by Skinnytorus** [opentoonz/kumoworks#12]
Hello, developers.

This is a wonderful app and I'm really happy to at last have an easy way of rendering realistic clouds. I refer to this bug which was happily fixed: https://github.com/opentoonz/kumoworks/issues/6 which I consider critical. 

The problem is that I'm not into compiling stuff at all and I'm not sure I'll be able to set up the building environment coreclty. Besides, I just don't need all these apps in my everyday PC life (like Visual Studio Express 2015 for Windows Desktop, CMake, Qt 5.9.2, Anaconda, Inno Setup) and therefore I see no reason in littering my HDD with programmer-specific software. 

So... You would make me (and perhaps lamers like me:) a bit happier if you would publish a new binary in your release section. Thank you and keep up the good work.

Skinny

**Comment by shun-iwasawa** [comment]
Hi @Skinnytorus  thank you for using KumoWorks!
I'll update the binary release.
