### ISSUE TITLE
Can KumoWorks be used for commercial projects?

### ISSUE THREAD

**Issue by simonschreibt-code** [opentoonz/kumoworks#21]
I'm writing here because I'm sure many other people have the same question and it's not clearly stated anywhere yet:

**Can KumoWorks be used for commercial projects?**

I tried to read Terms of Use but it's really hard to understand exactly what they mean and they do not contain the words "commercial", "free" or "cost". It only declares that one should not use the software for e.g. "criminal acts" but it says nowhere if commercial is is either allowed or forbidden.
For OpenToonz it is clearly stated on the website "OpenToonz can be used free of charge for both commercial and non-commercial projects." but I couldn't find this information about KumoWorks.

Could you please clarify that? Thank you!

**Comment by shun-iwasawa** [comment]
The terms of use for KumoWorks is very similar to the one for OpenToonz, and **YES**, you can use it free of charge for both commercial and non-commercial projects.
